name: Run lint and tests

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run lint and test
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v2

      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Run lint
        run: deno lint

      - name: Run test
        run: deno test